version: "3"
services:
  nginx:
    restart: always
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ui
      - api
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
  _build:
    image: mardam-image
    command: ["echo", "build completed"]
    build:
      context: .
      dockerfile: Dockerfile
  ui:
    image: mardam-image
    depends_on:
      - _build
    container_name: mardam-ui
    entrypoint: ["yarn", "workspace", "client", "start"]
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
      - /home/app/node_modules
  api:
    image: mardam-image
    depends_on:
      - _build
    container_name: mardam-api
    environment:
      JWT_SECRET: mardam
      DATABASE_NAME: mardam-dev
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    entrypoint: ["yarn", "workspace", "server", "dev"]
    ports:
      - "8080:8080"
    volumes:
      - .:/home/app
      - /home/app/node_modules
